[2023-11-29T16:50:35.039+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_upload_2.upload_to_s3 manual__2023-11-29T16:49:28.394080+00:00 [queued]>
[2023-11-29T16:50:35.240+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_upload_2.upload_to_s3 manual__2023-11-29T16:49:28.394080+00:00 [queued]>
[2023-11-29T16:50:35.251+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-29T16:50:35.642+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2023-11-29 16:49:28.394080+00:00
[2023-11-29T16:50:35.652+0000] {standard_task_runner.py:57} INFO - Started process 3251 to run task
[2023-11-29T16:50:35.664+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 's3_upload_2', 'upload_to_s3', 'manual__2023-11-29T16:49:28.394080+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/hook.py', '--cfg-path', '/tmp/tmpjjbzq4ue']
[2023-11-29T16:50:35.721+0000] {standard_task_runner.py:85} INFO - Job 80: Subtask upload_to_s3
[2023-11-29T16:50:38.021+0000] {task_command.py:416} INFO - Running <TaskInstance: s3_upload_2.upload_to_s3 manual__2023-11-29T16:49:28.394080+00:00 [running]> on host a89a99bc45b2
[2023-11-29T16:50:41.700+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Dashrath' AIRFLOW_CTX_DAG_ID='s3_upload_2' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-11-29T16:49:28.394080+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-29T16:49:28.394080+00:00'
[2023-11-29T16:50:41.926+0000] {base.py:73} INFO - Using connection ID 'aws_conn' for task execution.
[2023-11-29T16:50:41.944+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_conn', conn_type='aws') credentials retrieved from login and password.
[2023-11-29T16:50:59.101+0000] {logging_mixin.py:154} INFO - File uploaded to S3.
[2023-11-29T16:50:59.109+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-29T16:50:59.323+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=s3_upload_2, task_id=upload_to_s3, execution_date=20231129T164928, start_date=20231129T165035, end_date=20231129T165059
[2023-11-29T16:50:59.536+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-29T16:50:59.702+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
